"use client";
import { useEffect, useState } from "react";
import { api, response } from "@/lib/api";

interface Schedule {enabled:boolean;local_time:string;timezone:string;send:boolean}
interface Automation {task_mode:string;delivery_transport:string;recipient:string;worker_online:boolean;schedule:Schedule;delivery_note:string}
interface Delivery {id:string;brief_id:string;subject:string;status:string;transport:string;attempts:number;last_error:string|null;artifact_name:string|null}
const errorText=(error:unknown)=>error instanceof Error?error.message:"请求失败";

export function AutomationPanel(){
 const [status,setStatus]=useState<Automation|null>(null),[schedule,setSchedule]=useState<Schedule|null>(null);
 const [deliveries,setDeliveries]=useState<Delivery[]>([]),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 const reload=async()=>{const [s,d]=await Promise.all([api<Automation>("/automation"),api<Delivery[]>("/deliveries")]);setStatus(s);setDeliveries(d);return s;};
 useEffect(()=>{let active=true;Promise.all([api<Automation>("/automation"),api<Delivery[]>("/deliveries")]).then(([s,d])=>{if(active){setStatus(s);setSchedule(s.schedule);setDeliveries(d);}}).catch(e=>{if(active)setNotice(errorText(e));});return()=>{active=false;};},[]);
 const act=async(fn:()=>Promise<void>)=>{setBusy(true);try{await fn();}catch(e){setNotice(errorText(e));}finally{setBusy(false);}};
 const daily=()=>act(async()=>{if(schedule?.send&&status?.delivery_transport==="smtp"&&!window.confirm(`向已配置的 ${status.recipient} 发送本次简报？模型草稿仍须审核。`))return;const result=await api<{run_id:string}>("/automation/run",{method:"POST",body:JSON.stringify({send:schedule?.send??false,idempotency_key:crypto.randomUUID()})});setNotice(`每日流程已入队：${result.run_id}。可在运行记录查看，不表示已经发送。`);await reload();});
 const preview=(id:string)=>act(async()=>{const r=await response(`/deliveries/${id}/preview`);const url=URL.createObjectURL(await r.blob());const a=document.createElement("a");a.href=url;a.download=`${id}.eml`;a.click();URL.revokeObjectURL(url);});
 const resolve=(id:string,resolution:"confirmed_sent"|"confirmed_not_sent")=>act(async()=>{if(!window.confirm(resolution==="confirmed_sent"?"确认已经从邮件服务商日志确认发送成功？":"确认服务商没有接收这封邮件？错误确认可能造成重复发送。"))return;await api(`/deliveries/${id}/resolve`,{method:"POST",body:JSON.stringify({confirmed:true,resolution})});setNotice("已记录人工判定。");await reload();});
 return <><section className="intro"><div><div className="eyebrow">DURABLE DAILY PIPELINE</div><h1>每天准时，异常有据。</h1><p>独立 Worker、按时区调度、事务性发件箱。任务入队不等于已经发送。</p></div><button className="btn" disabled={busy} onClick={()=>act(async()=>{await reload();})}>刷新状态</button></section>
 {notice&&<div className="banner" role="status">{notice}</div>}
 <div className="banner"><strong>{status?.delivery_transport==="smtp"?"SMTP":"LOCAL FILE"}</strong><span>{status?.delivery_transport==="smtp"?"服务器接受邮件，不等于已送达收件箱；结果未知时禁止自动重发。":"只保存本地 .eml 预览，不发送邮件。演示资料不能使用 SMTP。"}</span></div>
 <section className="metrics"><div className="metric"><div className="label">任务执行</div><div className="value" style={{fontSize:22}}>{status?.task_mode??"读取中"}</div><div className="meta">数据库持久化；与 API 进程分离</div></div><div className="metric"><div className="label">Worker 心跳</div><div className="value" style={{fontSize:22}}>{status?.worker_online?"在线":"未检测到"}</div><div className="meta">离线时保留队列，不伪报执行成功</div></div><div className="metric"><div className="label">定时状态</div><div className="value" style={{fontSize:22}}>{status?.schedule.enabled?status.schedule.local_time:"未启用"}</div><div className="meta">{status?.schedule.timezone??"—"}</div></div></section>
 {schedule&&<form className="panel form-grid" onSubmit={e=>{e.preventDefault();void act(async()=>{await api("/automation/schedule",{method:"PUT",body:JSON.stringify(schedule)});await reload();setNotice("调度设置已保存。仅处理当前当地日期，不追发过去多天。");});}}><h2>每日调度</h2><label className="check"><input type="checkbox" checked={schedule.enabled} onChange={e=>setSchedule({...schedule,enabled:e.target.checked})}/>启用每日流程</label><label className="field">当地执行时间<input type="time" required value={schedule.local_time} onChange={e=>setSchedule({...schedule,local_time:e.target.value})}/></label><label className="field">调度时区<input required value={schedule.timezone} onChange={e=>setSchedule({...schedule,timezone:e.target.value})}/><small>调度时区独立于简报显示时区；需要一致时分别设置。</small></label><label className="check"><input type="checkbox" checked={schedule.send} onChange={e=>setSchedule({...schedule,send:e.target.checked})}/>生成后加入发件箱（当前为 {status?.delivery_transport}）</label><div className="actions"><button className="btn primary" disabled={busy}>保存调度</button><button type="button" className="btn" disabled={busy||status?.task_mode!=="durable"} onClick={daily}>立即运行一次每日流程</button></div><small>夏令时重复小时只执行一次；跳过的时间顺延至首个有效分钟。电脑休眠或 Worker 停止时无法准时执行。</small></form>}
 <div className="section-head" style={{marginTop:28}}><h2>发件箱记录</h2><span className="sub">file_written 是本地文件，不是已发送邮件</span></div><div className="panel table-wrap"><table><thead><tr><th>简报</th><th>状态</th><th>尝试</th><th>操作 / 说明</th></tr></thead><tbody>{deliveries.map(d=><tr key={d.id}><td>{d.subject}</td><td><span className="pill">{d.status}</span></td><td>{d.attempts}</td><td>{d.status==="file_written"&&<button className="btn small" disabled={busy} onClick={()=>preview(d.id)}>查看 .eml 预览</button>}{d.status==="unknown"&&<><button className="btn small" disabled={busy} onClick={()=>resolve(d.id,"confirmed_sent")}>确认已发送</button><button className="btn small" disabled={busy} onClick={()=>resolve(d.id,"confirmed_not_sent")}>确认未发送，允许重试</button></>}{d.last_error&&<p>{d.last_error}</p>}</td></tr>)}</tbody></table>{deliveries.length===0&&<div className="empty"><p>暂无发件箱记录。先运行每日流程，并勾选加入发件箱。</p></div>}</div></>;
}
