"use client";
import { useEffect, useRef, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api, nullable, response, safeUrl, streamEvidence } from "@/lib/api";
import { ResearchPanel, UpdatesPanel } from "./research-panel";
import { AutomationPanel } from "./automation-panel";
import { sliceCodePoints } from "@/lib/unicode";
import type { Answer, Brief, BriefItem, Citation, Edition, Preferences, Run, Snapshot, Source, Status } from "@/lib/types";

type View="brief"|"research"|"sources"|"history"|"runs"|"settings"|"automation"|"agent"|"updates";
const NAV:[View,string,string][]=[["brief","▤","每日简报"],["research","⌕","证据检索"],["updates","↗","增量阅读"],["agent","◇","研究助手"],["sources","◉","信息来源"],["history","◷","历史版本"],["runs","☷","运行记录"],["automation","◴","每日自动化"],["settings","⚙","偏好设置"]];
const TOPICS=["LLM","Agent","开源","论文","多模态","其他"];
function dates(value:string|null|undefined,zone="America/Los_Angeles"){return value?new Date(value).toLocaleString("zh-CN",{timeZone:zone,hour12:false}):"尚未获取";}
function message(error:unknown){return error instanceof Error?error.message:"请求失败";}
function Intro({title,subtitle,children}:{title:React.ReactNode;subtitle:string;children?:React.ReactNode}){return <section className="intro"><div><div className="eyebrow">YOUR DAILY SIGNAL</div><h1>{title}</h1><p>{subtitle}</p></div><div className="actions">{children}</div></section>;}
function Banner({status}:{status?:Status}){return <div className="banner"><strong>{status?.data_mode==="replay"?"REPLAY":"LIVE SOURCES"}</strong><span>{status?.data_mode==="replay"?"以下全部内容是合成测试样本，不是真实资讯。与 live 数据库严格隔离。":status?.generation_mode==="live"?"模型内容先进入待复核状态；引句匹配不等于事实核验。":"原文摘录模式：不调用 LLM、不自动翻译，也不把来源表述当作已独立核实的事实。"}</span></div>;}

export function Dashboard(){
 const qc=useQueryClient();const [view,setView]=useState<View>("brief"),[edition,setEdition]=useState<string|null>(null),[notice,setNotice]=useState("");
 const [selected,setSelected]=useState<BriefItem|null>(null),[token,setToken]=useState("");const tokenDialog=useRef<HTMLDialogElement>(null);
 const status=useQuery({queryKey:["status"],queryFn:()=>api<Status>("/status")});
 const sources=useQuery({queryKey:["sources"],queryFn:()=>api<Source[]>("/sources")});
 const prefs=useQuery({queryKey:["preferences"],queryFn:()=>api<Preferences>("/preferences")});
 const brief=useQuery({queryKey:["brief",edition],queryFn:()=>nullable<Brief>(edition?`/briefs/${edition}`:"/briefs/latest")});
 const history=useQuery({queryKey:["history"],queryFn:()=>api<Edition[]>("/briefs"),enabled:view==="history"});
 const runs=useQuery({queryKey:["runs"],queryFn:()=>api<Run[]>("/runs"),enabled:view==="runs",refetchInterval:view==="runs"?2000:false});
 const tz=prefs.data?.timezone;
 const refresh=async()=>{await Promise.all(["status","sources","brief","history","runs"].map(key=>qc.invalidateQueries({queryKey:[key]})));};
 const run=useMutation({mutationFn:async(kind:"ingest"|"brief")=>{
   const started=await api<{run_id:string}>("/runs",{method:"POST",body:JSON.stringify({kind})});setNotice("任务已提交，可在运行记录查看进度");
   for(let i=0;i<240;i++){const current=await api<Run>(`/runs/${started.run_id}`);if(!["queued","running"].includes(current.status))return current;await new Promise(r=>setTimeout(r,1500));}
   throw new Error("已停止前端轮询；请在运行记录检查任务状态");
 },onSuccess:async r=>{setNotice(`任务状态：${r.status}`);setEdition(null);await refresh();},onError:e=>setNotice(message(e))});
 const bookmark=useMutation({mutationFn:(item:BriefItem)=>api(`/articles/${item.article_id}/bookmark`,{method:"PATCH",body:JSON.stringify({bookmarked:!item.bookmarked})}),onSuccess:refresh,onError:e=>setNotice(message(e))});
 const toggle=useMutation({mutationFn:(s:Source)=>api(`/sources/${s.id}`,{method:"PATCH",body:JSON.stringify({enabled:!s.enabled})}),onSuccess:refresh,onError:e=>setNotice(message(e))});
 const exportBrief=async()=>{if(!brief.data)return;try{const r=await response(`/briefs/${brief.data.id}/markdown`);const url=URL.createObjectURL(await r.blob());const a=document.createElement("a");a.href=url;a.download=`ai-pulse-${brief.data.local_date}.md`;a.click();URL.revokeObjectURL(url);}catch(e){setNotice(message(e));}};
 const approve=async()=>{if(!brief.data||!window.confirm("确认已逐条对照原文核对模型草稿？此操作不表示完成了独立事实核验。"))return;try{await api(`/briefs/${brief.data.id}/approve`,{method:"POST",body:JSON.stringify({reviewed:true})});await refresh();}catch(e){setNotice(message(e));}};
 const queryError=status.error||sources.error||prefs.error||brief.error||(view==="runs"&&runs.error)||(view==="history"&&history.error);
 return <div className="shell"><aside className="sidebar"><div className="brand"><span className="brand-icon">∿</span><div>AI Pulse<small>LESS NOISE. MORE SIGNAL.</small></div></div><div className="nav-label">WORKSPACE</div><nav aria-label="主导航">{NAV.map(([key,icon,label])=><button key={key} className={`nav-btn ${view===key?"active":""}`} onClick={()=>{setView(key);if(key==="brief")setEdition(null);}}><span className="nav-icon">{icon}</span>{label}</button>)}</nav><div className="side-note"><strong>从信息，到有据可查。</strong>保留来源与证据位置。<br/>把“原文这么说”与“已经证实”分开。</div><div className="version">v0.4.0-dev / NEXT.JS WORKSPACE</div></aside>
 <main className="main"><header className="topbar"><div className="breadcrumb">工作台　/　<strong>{NAV.find(x=>x[0]===view)?.[2]}</strong></div><div className="top-actions"><span className={`pill ${status.data?.data_mode==="replay"?"orange":"green"}`}><span className="dot"/>{status.data?.data_mode.toUpperCase()??"CONNECTING"} · {status.data?.generation_mode.toUpperCase()??"—"}</span><button className="btn small" onClick={()=>tokenDialog.current?.showModal()}>访问令牌</button></div></header>
 {queryError&&<div className="banner error" role="alert" style={{marginTop:20}}>{message(queryError)}</div>}
 {notice&&<div className="banner" role="status" style={{marginTop:20}}><span>{notice}</span><button onClick={()=>setNotice("")} aria-label="关闭通知">×</button></div>}
 {view==="brief"&&<><Intro title={<>让值得关注的变化，<br/>先到你眼前。</>} subtitle="按你的关注方向筛选，保留每条内容的来源与证据。"><button className="btn" disabled={run.isPending||status.data?.data_mode!=="live"} onClick={()=>run.mutate("ingest")}>↻ 采集来源</button><button className="btn primary" disabled={run.isPending||!status.data} onClick={()=>run.mutate("brief")}>{run.isPending?"任务执行中…":"生成简报 ↗"}</button></Intro><Banner status={status.data}/>
 <section className="metrics">{[["已保存资料",status.data?.articles??"—","不可变快照与原文位置"],["本版简报",brief.data?.items.length??0,`近 ${prefs.data?.lookback_hours??72} 小时 · 精确内容去重`],["启用来源",sources.data?.filter(s=>s.enabled).length??0,status.data?.generation_mode==="live"?"模型草稿待复核":"原文摘录 · 模型调用 0 次"]].map(([label,value,meta])=><div className="metric" key={label}><div className="label">{label}</div><div className="value">{value}</div><div className="meta">{meta}</div></div>)}</section>
 <div className="grid-main"><section><div className="section-head"><h2>每日简报 <span className="sub">/ {brief.data?.local_date??"尚未生成"}</span></h2>{brief.data&&<button className="btn small" onClick={exportBrief}>导出 Markdown</button>}</div>
 {brief.data?.status==="needs_review"&&<div className="pending">模型草稿还未经过人工复核，不能作为正式简报导出。<br/><button className="btn small" onClick={approve}>已逐条核对，批准导出</button></div>}
 <div className="article-list">{brief.data?.items.length?brief.data.items.map((item,index)=><article className={`article ${index===0?"featured":""}`} key={item.id}><div className="article-top"><div className="source-label"><span className="topic">{item.topic}</span>{item.source_name}<span>· {dates(item.published_at,tz)}</span></div><span className="number">{String(index+1).padStart(2,"0")}</span></div><h3>{item.title}</h3><p className="summary">{item.summary}</p><div className="relevance">↳ {item.relevance_reason}</div><div className="article-bottom"><button className="evidence-btn" onClick={()=>setSelected(item)}>▧ 查看来源与证据 ↗</button><div><span className="pill green">{item.verification==="exact_excerpt"?"原文摘录":"引句匹配 · 非事实核验"}</span><button className={`bookmark-btn ${item.bookmarked?"saved":""}`} disabled={bookmark.isPending} onClick={()=>bookmark.mutate(item)}>{item.bookmarked?"★ 已收藏":"☆ 收藏"}</button></div></div></article>):<div className="empty"><h3>{brief.isPending?"正在读取简报…":brief.data?"当前窗口没有可用资讯":"你的第一份简报，从这里开始"}</h3><p>先采集真实来源，再生成简报。不会用旧闻、未知日期或未来日期的文章凑数，也不会自动替换为演示数据。</p></div>}</div></section>
 <aside className="rail"><div className="panel dark"><div className="label">EVIDENCE FIRST</div><h3 style={{fontSize:18,margin:"13px 0"}}>不是更多资讯，<br/>而是更清楚的依据。</h3><p>关键内容关联到存储快照。来源更新，不会改写旧简报中的原文证据。</p><div className="line"/><p>引用存在 ≠ 结论已被证实</p></div><div className="panel"><h3>我的关注</h3><div className="tag-list">{prefs.data?.topics.map(t=><span className="tag" key={t}>{t}</span>)}</div><div className="line"/><p>显示时区<br/>{tz}</p></div><div className="panel"><h3>来源状态</h3>{sources.data?.map(s=><div className="mini-row" key={s.id}><span>{s.name}</span><span className="muted">{!s.enabled?"停用":s.last_error?"失败":s.last_success_at?"已采集":"未采集"}</span></div>)}<p style={{marginTop:12}}>截至 {dates(brief.data?.cutoff_at,tz)}<br/>自动化与发件箱状态请查看「每日自动化」。</p></div></aside></div></>}
 {view==="automation"&&<AutomationPanel/>}
 {view==="agent"&&<ResearchPanel/>}
 {view==="updates"&&<UpdatesPanel/>}
 {view==="sources"&&<><Intro title="每条信息，都有来处。" subtitle="固定审核列表中的 RSS、Atom 与 GitHub Releases；不接受任意抓取 URL。"><button className="btn primary" disabled={run.isPending||status.data?.data_mode!=="live"} onClick={()=>run.mutate("ingest")}>↻ 采集来源</button></Intro><Banner status={status.data}/><div className="sources-grid">{sources.data?.map(s=><article className="panel source-card" key={s.id}><div><span className="pill">{s.kind.toUpperCase()}</span><h3 style={{margin:"12px 0 2px"}}>{s.name}</h3><p><code>{s.url}</code><br/>最后尝试：{dates(s.last_attempt_at,tz)}<br/>最后成功：{dates(s.last_success_at,tz)}<br/>连续失败：{s.failure_count}</p>{s.last_error&&<div className="banner error">{s.last_error}</div>}</div><button className="btn small" disabled={toggle.isPending} onClick={()=>toggle.mutate(s)}>{s.enabled?"停用来源":"启用来源"}</button></article>)}</div></>}
 {view==="history"&&<><Intro title="每一版，都保留当时的依据。" subtitle="读取生成时的快照，不用新内容覆盖旧证据。"/><div className="panel table-wrap"><table><thead><tr><th>简报日期</th><th>生成时间</th><th>模式</th><th>状态</th><th/></tr></thead><tbody>{history.data?.map(b=><tr key={b.id}><td>{b.local_date}</td><td>{dates(b.created_at,tz)}</td><td>{b.data_mode} / {b.generation_mode}</td><td>{b.status}</td><td><button className="btn small" onClick={()=>{setEdition(b.id);setView("brief");}}>查看版本</button></td></tr>)}</tbody></table>{history.data?.length===0&&<p className="empty">尚无历史简报。</p>}</div></>}
 {view==="runs"&&<><Intro title="执行过程，不是黑箱。" subtitle="本地任务的每一步都有记录；进程中断后需重新发起。"/>{runs.data?.map(r=><details className="panel run" key={r.id} open><summary><span className={`pill ${r.status==="succeeded"?"green":"orange"}`}>{r.status}</span><strong>{r.kind==="brief"?"生成简报":"采集来源"}</strong><span className="muted">{dates(r.created_at,tz)}</span></summary>{r.error&&<div className="banner error">{r.error}</div>}<div className="timeline">{r.events.map((e,i)=><div key={i}><code>{e.stage}</code>{e.message}</div>)}</div></details>)}{runs.data?.length===0&&<div className="empty"><p>尚未执行任务。</p></div>}</>}
 {view==="research"&&<Research status={status.data} tz={tz}/>}
 {view==="settings"&&prefs.data&&<SettingsForm key={JSON.stringify(prefs.data)} preferences={prefs.data} onSaved={async()=>{await qc.invalidateQueries({queryKey:["preferences"]});setNotice("偏好已保存，下次生成时生效");}}/>}
 <footer className="footnote">AI Pulse · Evidence before conclusions.<br/>Next.js + React + TanStack Query · 单用户本地开发版</footer></main>
 {selected&&<Evidence item={selected} onClose={()=>setSelected(null)} tz={tz}/>}
 <dialog ref={tokenDialog} aria-labelledby="token-title"><div className="dialog-header"><h2 id="token-title">工作台访问令牌</h2><button className="btn small" onClick={()=>tokenDialog.current?.close()}>关闭</button></div><form className="dialog-body" onSubmit={async e=>{e.preventDefault();sessionStorage.setItem("pulse-token",token.trim());setToken("");tokenDialog.current?.close();await qc.invalidateQueries();}}><label className="field">ADMIN_TOKEN<input type="password" autoComplete="off" value={token} onChange={e=>setToken(e.target.value)}/><small>仅保存在当前标签页 sessionStorage；模型密钥始终只在服务端。</small></label><button className="btn primary" style={{marginTop:16}}>保存并连接</button></form></dialog></div>;
}

function Evidence({item,onClose,tz}:{item:BriefItem;onClose:()=>void;tz?:string}){
 const dialog=useRef<HTMLDialogElement>(null);const snap=useQuery({queryKey:["snapshot",item.snapshot_id],queryFn:()=>api<Snapshot>(`/snapshots/${item.snapshot_id}`)});
 useEffect(()=>{dialog.current?.showModal();},[]);
 return <dialog ref={dialog} onClose={onClose} aria-labelledby="evidence-title"><div className="dialog-header"><h2 id="evidence-title">来源与证据</h2><button className="btn small" aria-label="关闭证据" onClick={onClose}>关闭 ×</button></div><div className="dialog-body">{snap.error&&<p role="alert">{message(snap.error)}</p>}{snap.data?<><span className="pill green">{item.verification}</span><h3 style={{marginTop:16}}>{snap.data.title}</h3><blockquote className="quote">{item.evidence_quote}</blockquote><p style={{fontSize:11,lineHeight:2,color:"var(--muted)"}}>快照 ID：{snap.data.id}<br/>字符区间：[{item.quote_start}, {item.quote_end})<br/>采集时间：{dates(snap.data.captured_at,tz)}<br/>保存范围：{snap.data.scope}（不是网页全文核验）<br/>SHA-256：<span style={{wordBreak:"break-all"}}>{snap.data.content_hash}</span></p><div className="line"/><a className="btn small" href={safeUrl(snap.data.source_url)} target="_blank" rel="noreferrer noopener">打开原始来源 ↗</a><div className="line"/><h3>存储文本</h3><p className="snapshot-text">{sliceCodePoints(snap.data.text,0,item.quote_start)}<mark>{sliceCodePoints(snap.data.text,item.quote_start,item.quote_end)}</mark>{sliceCodePoints(snap.data.text,item.quote_end)}</p></>:!snap.error&&<p>正在读取快照…</p>}</div></dialog>;
}
function SettingsForm({preferences,onSaved}:{preferences:Preferences;onSaved:()=>Promise<void>}){
 const [prefs,setPrefs]=useState(preferences),[error,setError]=useState("");
 const save=useMutation({mutationFn:()=>api<Preferences>("/preferences",{method:"PUT",body:JSON.stringify(prefs)}),onSuccess:onSaved,onError:e=>setError(message(e))});
 return <><Intro title="让简报更贴近你的关注。" subtitle="偏好只改变选择与排序，不改写事实。"/><form className="panel form-grid" onSubmit={e=>{e.preventDefault();setError("");save.mutate();}}><label className="field">显示时区<input value={prefs.timezone} required onChange={e=>setPrefs({...prefs,timezone:e.target.value})}/><small>IANA 时区，例如 Asia/Shanghai 或 America/Los_Angeles。</small></label><div className="field"><span>优先关注主题</span><div className="checks">{TOPICS.map(t=><label className="check" key={t}><input type="checkbox" checked={prefs.topics.includes(t)} onChange={e=>setPrefs({...prefs,topics:e.target.checked?[...prefs.topics,t]:prefs.topics.filter(x=>x!==t)})}/>{t}</label>)}</div></div><label className="field">单份条目上限（1–12）<input type="number" min={1} max={12} required value={prefs.max_items} onChange={e=>setPrefs({...prefs,max_items:Number(e.target.value)})}/></label><label className="field">回溯窗口 / 小时（1–168）<input type="number" min={1} max={168} required value={prefs.lookback_hours} onChange={e=>setPrefs({...prefs,lookback_hours:Number(e.target.value)})}/></label><label className="field">排除关键词，每行一个<textarea rows={3} value={prefs.blocked_keywords.join("\n")} onChange={e=>setPrefs({...prefs,blocked_keywords:e.target.value.split("\n")})}/></label>{error&&<p role="alert" className="banner error">{error}</p>}<div><button className="btn primary" disabled={save.isPending}>保存偏好</button></div></form></>;
}
function Research({status,tz}:{status?:Status;tz?:string}){
 const [question,setQuestion]=useState(""),[citations,setCitations]=useState<Citation[]>([]),[answer,setAnswer]=useState<Answer|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const controller=useRef<AbortController|null>(null);useEffect(()=>()=>controller.current?.abort(),[]);
 return <><Intro title="带着问题，回到证据。" subtitle="本地词项检索，不联网搜索、不自动生成推断结论。"/><Banner status={status}/><div className="panel"><div className="label">LOCAL EVIDENCE SEARCH · SSE</div><form className="query-form" onSubmit={async e=>{e.preventDefault();controller.current?.abort();controller.current=new AbortController();setBusy(true);setCitations([]);setAnswer(null);setError("");try{const result=await streamEvidence(question,c=>setCitations(old=>[...old,c]),controller.current.signal);setAnswer(result);}catch(err){if(!(err instanceof DOMException&&err.name==="AbortError"))setError(message(err));}finally{setBusy(false);}}}><input className="query-input" aria-label="检索问题" placeholder="例如：Agent 工作流如何记录任务状态？" required minLength={2} maxLength={400} value={question} onChange={e=>setQuestion(e.target.value)}/><button className="btn primary" disabled={busy}>{busy?"检索中…":"检索证据 ↗"}</button></form><div className="tag-list"><span className="tag">中文双字片段</span><span className="tag">英文词项</span><span className="tag">原文字符定位</span></div><div className="answer" aria-live="polite">{error&&<p className="banner error">{error}</p>}{answer&&<p style={{fontSize:12,lineHeight:1.9}}>{answer.answer}</p>}{citations.map((c,i)=><article key={c.snapshot_id} style={{marginTop:22}}><h3 style={{fontSize:14}}>[{i+1}] {c.title}</h3><blockquote className="quote">{c.quote}</blockquote><div className="source-label"><a href={safeUrl(c.url)} target="_blank" rel="noopener noreferrer">{c.source_name} ↗</a>字符 [{c.quote_start}, {c.quote_end}) · {dates(c.published_at,tz)}</div></article>)}</div></div></>;
}
