"use client";
import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api, safeUrl } from "@/lib/api";
import type { Citation } from "@/lib/types";
interface Investigation {id:string;question:string;status:string;data_mode:string;generation_mode:string;trace:{stage:string;message:string;tool?:string}[];result:{answer?:string;tool_calls?:number;model_calls?:number;stop_reason?:string;citations?:(Citation & {evidence_id:string})[]}}
interface UpdateItem {article_id:string;title:string;snapshot_id:string;status:"read"|"unread"|"changed_since_read";topic:string}
interface Changes {title:string;status:string;note:string;baseline_snapshot_id:string|null;target_snapshot_id:string;title_changed:boolean;baseline_title:string|null;truncated:boolean;changes:{kind:string;text:string;start:number;end:number}[]}
const labels={read:"本版已读",unread:"未读",changed_since_read:"已读后有变化"};
function failure(e:unknown){return e instanceof Error?e.message:"请求失败";}
export function ResearchPanel(){
 const [question,setQuestion]=useState("");const [budget,setBudget]=useState(3);const [selected,setSelected]=useState<Investigation|null>(null);const qc=useQueryClient();
 const history=useQuery({queryKey:["investigations"],queryFn:()=>api<Investigation[]>("/investigations")});
 const run=useMutation({mutationFn:()=>api<Investigation>("/investigations",{method:"POST",body:JSON.stringify({question,max_tool_calls:budget,idempotency_key:crypto.randomUUID()})}),onSuccess:async result=>{setSelected(result);await qc.invalidateQueries({queryKey:["investigations"]});}});
 const result=selected?.result;
 return <><section className="intro"><div><div className="eyebrow">BOUNDED EVIDENCE WORKFLOW</div><h1>每一步研究，都有记录。</h1><p>有限工具、有限调用、证据校验。默认原文检索，不伪装成模型推理。</p></div></section><div className="banner">只读已保存资料。模型启用后仍只能调用两种本地只读工具；生成内容始终待人工复核。</div><form className="panel agent-form" onSubmit={e=>{e.preventDefault();run.mutate();}}><label className="field">研究问题<textarea aria-label="研究问题" minLength={2} maxLength={400} required rows={3} value={question} onChange={e=>setQuestion(e.target.value)}/></label><div className="agent-form-bottom"><label className="field">工具调用上限<select value={budget} onChange={e=>setBudget(Number(e.target.value))}>{[1,2,3,4].map(n=><option key={n}>{n}</option>)}</select></label><button className="btn primary" disabled={run.isPending}>{run.isPending?"正在执行证据研究…":"开始证据研究 ↗"}</button></div></form>{(run.error||history.error)&&<div className="banner error">{failure(run.error||history.error)}</div>}
 {selected&&<article className="panel investigation"><div className="article-top"><span className="pill">{selected.data_mode.toUpperCase()} / {selected.generation_mode}</span><span className="pill">{selected.status}</span></div><h2>{selected.question}</h2><div className="agent-counts"><span>工具调用 <b>{result?.tool_calls??0}</b></span><span>模型调用 <b>{result?.model_calls??0}</b></span><span>证据 <b>{result?.citations?.length??0}</b></span></div><p className="agent-answer">{result?.answer??"执行中；刷新研究记录可检查状态。"}</p>{selected.status==="needs_review"&&<div className="pending">模型生成草稿尚未人工复核，不会自动发送。</div>}{result?.citations?.map(c=><div className="evidence-block" key={c.evidence_id}><span className="pill">{c.evidence_id}</span> <a href={safeUrl(c.url)} target="_blank" rel="noopener noreferrer">{c.source_name} · {c.title}</a><blockquote>{c.quote}</blockquote><small>快照 {c.snapshot_id.slice(0,8)} · 字符 {c.quote_start}–{c.quote_end}</small></div>)}<details className="trace-details" open><summary>已保存的执行记录 · {result?.stop_reason??"running"}</summary><div className="timeline">{selected.trace.map((event,i)=><div key={i}><code>{event.stage}</code>{event.message} {event.tool&&<small>{event.tool}</small>}</div>)}</div></details></article>}
 <div className="section-head"><h2>最近研究记录</h2><button className="btn small" onClick={()=>history.refetch()}>刷新记录</button></div>{history.data?.map(row=><button className="panel agent-history-item" key={row.id} onClick={()=>setSelected(row)}><strong>{row.question}</strong><span>{row.status}</span></button>)}</>;
}
export function UpdatesPanel(){
 const qc=useQueryClient();const [only,setOnly]=useState(false),[delta,setDelta]=useState<Changes|null>(null),[error,setError]=useState("");
 const rows=useQuery({queryKey:["updates"],queryFn:()=>api<UpdateItem[]>("/updates")});
 const mark=useMutation({mutationFn:({row,unread}:{row:UpdateItem;unread:boolean})=>api(`/articles/${row.article_id}/read`,{method:unread?"DELETE":"PUT",body:unread?undefined:JSON.stringify({snapshot_id:row.snapshot_id})}),onSuccess:async()=>{setDelta(null);await Promise.all([qc.invalidateQueries({queryKey:["updates"]}),qc.invalidateQueries({queryKey:["brief"]})]);}});
 async function compare(row:UpdateItem){try{setDelta(await api<Changes>(`/articles/${row.article_id}/changes`));setError("");}catch(e){setError(failure(e));}}
 return <><section className="intro"><div><div className="eyebrow">READ ONCE. FOLLOW THE CHANGE.</div><h1>只看读过之后，新增的内容。</h1><p>保存已读快照，展示原文差异；不是语义事件聚类或独立事实核验。</p></div></section>{(rows.error||mark.error||error)&&<div className="banner error">{error||failure(rows.error||mark.error)}</div>}<div className="section-head"><h2>阅读队列</h2><label><input type="checkbox" checked={only} onChange={e=>setOnly(e.target.checked)}/> 只看已读后变化</label></div><div className="article-list">{rows.data?.filter(r=>!only||r.status==="changed_since_read").map(row=><article className="article" key={row.article_id}><div className="article-top"><span className="topic">{row.topic}</span><span className="pill">{labels[row.status]}</span></div><h3>{row.title}</h3><div className="article-bottom"><button className="btn small" onClick={()=>compare(row)}>查看文本变化</button><button className="btn small" disabled={mark.isPending} onClick={()=>mark.mutate({row,unread:false})}>标记本版已读</button><button className="btn small" disabled={mark.isPending} onClick={()=>mark.mutate({row,unread:true})}>设为未读</button></div></article>)}</div>{delta&&<section className="panel delta-panel"><div className="eyebrow">SNAPSHOT DIFF</div><h2>{delta.title}</h2><p>{delta.note}</p>{!delta.baseline_snapshot_id&&<p className="pending">尚未标记已读，没有比较基线。</p>}{delta.title_changed&&<p>标题变化：{delta.baseline_title} → {delta.title}</p>}{delta.changes.map((c,i)=><div className={`diff-line ${c.kind}`} key={i}><strong>{c.kind==="added"?"＋ 新增":"－ 移除"}</strong><p>{c.text}</p><small>字符 {c.start}–{c.end}</small></div>)}{delta.truncated&&<p className="pending">差异展示已达上限，请核对完整快照。</p>}{delta.status==="read"&&<p>目标版本与已读版本一致。</p>}</section>}</>;
}
