"""initial evidence-first schema
Revision ID: 0001
Revises: 
"""
from alembic import op
import sqlalchemy as sa

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('briefs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('local_date', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('cutoff_at', sa.String(length=40), nullable=False),
    sa.Column('window_start', sa.String(length=40), nullable=False),
    sa.Column('timezone', sa.String(length=70), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('data_mode', sa.String(length=20), nullable=False),
    sa.Column('generation_mode', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=150), nullable=True),
    sa.Column('prompt_version', sa.String(length=30), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('source_health', sa.JSON(), nullable=False),
    sa.Column('usage', sa.JSON(), nullable=False),
    sa.Column('approved_at', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint')
    )
    with op.batch_alter_table('briefs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_briefs_local_date'), ['local_date'], unique=False)

    op.create_table('runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('active_key', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('finished_at', sa.String(length=40), nullable=True),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('active_key')
    )
    op.create_table('sources',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_success_at', sa.String(length=40), nullable=True),
    sa.Column('last_attempt_at', sa.String(length=40), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_mode', sa.String(length=20), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('canonical_url', sa.Text(), nullable=False),
    sa.Column('source_id', sa.String(length=60), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('published_at', sa.String(length=40), nullable=True),
    sa.Column('updated_at', sa.String(length=40), nullable=True),
    sa.Column('first_seen_at', sa.String(length=40), nullable=False),
    sa.Column('event_time', sa.String(length=40), nullable=True),
    sa.Column('current_snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('topic', sa.String(length=30), nullable=False),
    sa.Column('bookmarked', sa.Boolean(), nullable=False),
    sa.Column('data_mode', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_url')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_articles_published_at'), ['published_at'], unique=False)

    op.create_table('fetch_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=60), nullable=False),
    sa.Column('started_at', sa.String(length=40), nullable=False),
    sa.Column('finished_at', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('counts', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('article_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('captured_at', sa.String(length=40), nullable=False),
    sa.Column('scope', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'content_hash')
    )
    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_snapshots_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_snapshots_content_hash'), ['content_hash'], unique=False)

    op.create_table('brief_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('brief_id', sa.String(length=36), nullable=False),
    sa.Column('article_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('source_name', sa.String(length=150), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('published_at', sa.String(length=40), nullable=True),
    sa.Column('topic', sa.String(length=30), nullable=False),
    sa.Column('evidence_quote', sa.Text(), nullable=False),
    sa.Column('quote_start', sa.Integer(), nullable=False),
    sa.Column('quote_end', sa.Integer(), nullable=False),
    sa.Column('verification', sa.String(length=40), nullable=False),
    sa.Column('relevance_reason', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['brief_id'], ['briefs.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brief_id', 'position')
    )
    with op.batch_alter_table('brief_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brief_items_brief_id'), ['brief_id'], unique=False)

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brief_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brief_items_brief_id'))

    op.drop_table('brief_items')
    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snapshots_content_hash'))
        batch_op.drop_index(batch_op.f('ix_snapshots_article_id'))

    op.drop_table('snapshots')
    op.drop_table('fetch_runs')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_published_at'))

    op.drop_table('articles')
    op.drop_table('workspace')
    op.drop_table('sources')
    op.drop_table('runs')
    with op.batch_alter_table('briefs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_briefs_local_date'))

    op.drop_table('briefs')
    # ### end Alembic commands ###
